package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTAuthPlus.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAuthPlus extends SimpleNode {
  public ASTAuthPlus(int id) {
    super(id);
  }

  public ASTAuthPlus(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b4e426a48e1afddda1526d3e71f9d063 (do not edit this line) */
