package com.ecs235.ponder;

/* Generated By:JJTree: Do not edit this line. ASTAuthStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAuthStatement extends SimpleNode {
  public ASTAuthStatement(int id) {
    super(id);
  }

  public ASTAuthStatement(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5f88f8a9e883c5d7cb35846ca8607e4a (do not edit this line) */
