package com.ecs235.ponder;

/* Generated By:JJTree: Do not edit this line. ASTAction.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAction extends SimpleNode {
  public ASTAction(int id) {
    super(id);
  }

  public ASTAction(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=41f2e515f390769192114d6103858241 (do not edit this line) */
