package com.ecs235.ponder;

/* Generated By:JJTree: Do not edit this line. ASTActionList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTActionList extends SimpleNode {
  public ASTActionList(int id) {
    super(id);
  }

  public ASTActionList(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=240d8edfa3be01e414fdb8665a5d4a92 (do not edit this line) */
