package com.ecs235.ponder;

/* Generated By:JJTree: Do not edit this line. ASTInstance.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInstance extends SimpleNode {
  public ASTInstance(int id) {
    super(id);
  }

  public ASTInstance(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=53ea18408166090b07cc7870e11defaa (do not edit this line) */
