package com.ecs235.ponder;

/* Generated By:JJTree: Do not edit this line. ASTPolicyContent.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPolicyContent extends SimpleNode {
  public ASTPolicyContent(int id) {
    super(id);
  }

  public ASTPolicyContent(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0aa4a5cf6044f39ddc15b3bb07f68599 (do not edit this line) */
