package com.ecs235.ponder;

/* Generated By:JJTree: Do not edit this line. ASTPolicyName.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPolicyName extends SimpleNode {
  public ASTPolicyName(int id) {
    super(id);
  }

  public ASTPolicyName(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d5366af8273f068d14c995260f0c187d (do not edit this line) */
