package com.ecs235.ponder;

/* Generated By:JJTree: Do not edit this line. ASTSubject.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSubject extends SimpleNode {
  public ASTSubject(int id) {
    super(id);
  }

  public ASTSubject(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e51960e46949bf549875e0a1894364cf (do not edit this line) */
