package com.ecs235.ponder;

/* Generated By:JJTree: Do not edit this line. ASTTarget.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTarget extends SimpleNode {
  public ASTTarget(int id) {
    super(id);
  }

  public ASTTarget(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8637550900ae72eecfcdc36938fb8e03 (do not edit this line) */
