package com.ecs235.ponder;

/* Generated By:JavaCC: Do not edit this line. PonderTreeConstants.java Version 7.0.10 */
public interface PonderTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPOLICYNAME = 1;
  public int JJTDOMAINSCOPEEXPRESSION = 2;
  public int JJTACTIONITEM = 3;
  public int JJTACTIONLIST = 4;
  public int JJTCONSTRAINTEXPRESSION = 5;
  public int JJTINSTANCE = 6;
  public int JJTAUTHPLUS = 7;
  public int JJTAUTHMINUS = 8;
  public int JJTTYPE = 9;
  public int JJTSUBJECT = 10;
  public int JJTTARGET = 11;
  public int JJTACTION = 12;
  public int JJTWHEN = 13;
  public int JJTPOLICYCONTENT = 14;
  public int JJTAUTHSTATEMENT = 15;


  public String[] jjtNodeName = {
    "Start",
    "PolicyName",
    "DomainScopeExpression",
    "ActionItem",
    "ActionList",
    "ConstraintExpression",
    "Instance",
    "AuthPlus",
    "AuthMinus",
    "Type",
    "Subject",
    "Target",
    "Action",
    "When",
    "PolicyContent",
    "AuthStatement",
  };
}
/* JavaCC - OriginalChecksum=f0f58acabcddb2d11af0e1855f30c523 (do not edit this line) */
