package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTAuthPolicy.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAuthPolicy extends SimpleNode {
  public ASTAuthPolicy(int id) {
    super(id);
  }

  public ASTAuthPolicy(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=85b19d58dc425687cd8caf4ba02dc68a (do not edit this line) */
