package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTAuthMinus.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAuthMinus extends SimpleNode {
  public ASTAuthMinus(int id) {
    super(id);
  }

  public ASTAuthMinus(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fc6a8cc53c15e6939a3899bc98d61d97 (do not edit this line) */
