package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTAuthPlusPolicyContent.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAuthPlusPolicyContent extends SimpleNode {
  public ASTAuthPlusPolicyContent(int id) {
    super(id);
  }

  public ASTAuthPlusPolicyContent(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b747266b74df603daaa4cdbe87049fdf (do not edit this line) */
