package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTActionOut.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTActionOut extends SimpleNode {
  public ASTActionOut(int id) {
    super(id);
  }

  public ASTActionOut(Ponder p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=bc1e13b9b7858b13867177e9f510e456 (do not edit this line) */
