package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTAuthMinusPolicyContent.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAuthMinusPolicyContent extends SimpleNode {
  public ASTAuthMinusPolicyContent(int id) {
    super(id);
  }

  public ASTAuthMinusPolicyContent(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eb6a7feda54f7803d8335ba3da8d1a22 (do not edit this line) */
