package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTActionItem.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTActionItem extends SimpleNode {
  public ASTActionItem(int id) {
    super(id);
  }

  public ASTActionItem(Ponder p, int id) {
    super(p, id);
  }

  private String name;

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "Action: " + name;
  }
}
/* JavaCC - OriginalChecksum=ec09083394eb8f1df14519c4dccbe0f6 (do not edit this line) */
