package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTActionIn.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTActionIn extends SimpleNode {
  public ASTActionIn(int id) {
    super(id);
  }

  public ASTActionIn(Ponder p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=17805ca6883d6bb8a882cfb6f08ef2df (do not edit this line) */
