package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTActionFilter.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTActionFilter extends SimpleNode {
  public ASTActionFilter(int id) {
    super(id);
  }

  public ASTActionFilter(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c83447e87ff813996b41c691aad56c8a (do not edit this line) */
