package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTActionResult.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTActionResult extends SimpleNode {
  public ASTActionResult(int id) {
    super(id);
  }

  public ASTActionResult(Ponder p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=879c78a343cb5fbfbe410cae49b5b881 (do not edit this line) */
