package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTActionCondition.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTActionCondition extends SimpleNode {
  public ASTActionCondition(int id) {
    super(id);
  }

  public ASTActionCondition(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b10414b8a1e900c9464e3fb884583862 (do not edit this line) */
