package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTConstraintExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConstraintExpression extends SimpleNode {
  public ASTConstraintExpression(int id) {
    super(id);
  }

  public ASTConstraintExpression(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3384a9464b24a3e80329bd38ce16581b (do not edit this line) */
