package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTParameterName.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParameterName extends SimpleNode {
  public ASTParameterName(int id) {
    super(id);
  }

  public ASTParameterName(Ponder p, int id) {
    super(p, id);
  }
  private String name;

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "ParameterName:" + name;
  }
}
/* JavaCC - OriginalChecksum=02a06be2216239425d1c9ec7576ef5c2 (do not edit this line) */
