package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTParameterValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParameterValue extends SimpleNode {
  public ASTParameterValue(int id) {
    super(id);
  }

  public ASTParameterValue(Ponder p, int id) {
    super(p, id);
  }
  private String name;

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "ParameterValue:" + name;
  }
}
/* JavaCC - OriginalChecksum=a3dd87d4a62bdefd692a107998e8ea92 (do not edit this line) */
