package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTPolicyStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPolicyStatement extends SimpleNode {
  public ASTPolicyStatement(int id) {
    super(id);
  }

  public ASTPolicyStatement(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0eacec951ccce4c97c05573ca2211a3c (do not edit this line) */
