package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTRefrain.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRefrain extends SimpleNode {
  public ASTRefrain(int id) {
    super(id);
  }

  public ASTRefrain(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=805e452c9ff9318dfb5803b60490b093 (do not edit this line) */
