package com.ucd.ecs235.compiler;

/* Generated By:JJTree: Do not edit this line. ASTRefrainPolicy.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRefrainPolicy extends SimpleNode {
  public ASTRefrainPolicy(int id) {
    super(id);
  }

  public ASTRefrainPolicy(Ponder p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f6d788bcd2c26df5b1b7712397b5e37d (do not edit this line) */
