package com.ucd.ecs235.compiler;

/* Generated By:JavaCC: Do not edit this line. PonderTreeConstants.java Version 7.0.10 */
public interface PonderTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPOLICYNAME = 1;
  public int JJTDOMAINSCOPEEXPRESSION = 2;
  public int JJTACTIONITEM = 3;
  public int JJTACTIONLIST = 4;
  public int JJTCONSTRAINTEXPRESSION = 5;
  public int JJTINSTANCE = 6;
  public int JJTAUTHPLUS = 7;
  public int JJTAUTHMINUS = 8;
  public int JJTTYPE = 9;
  public int JJTSUBJECT = 10;
  public int JJTTARGET = 11;
  public int JJTACTION = 12;
  public int JJTWHEN = 13;
  public int JJTAUTHPLUSPOLICYCONTENT = 14;
  public int JJTAUTHMINUSPOLICYCONTENT = 15;
  public int JJTAUTHPOLICY = 16;
  public int JJTPARAMETERNAME = 17;
  public int JJTPARAMETERVALUE = 18;
  public int JJTACTIONIN = 19;
  public int JJTACTIONOUT = 20;
  public int JJTACTIONRESULT = 21;
  public int JJTACTIONNAME = 22;
  public int JJTACTIONCONDITION = 23;
  public int JJTACTIONFILTER = 24;
  public int JJTREFRAIN = 25;
  public int JJTREFRAINPOLICY = 26;
  public int JJTPOLICYSTATEMENT = 27;


  public String[] jjtNodeName = {
    "Start",
    "PolicyName",
    "DomainScopeExpression",
    "ActionItem",
    "ActionList",
    "ConstraintExpression",
    "Instance",
    "AuthPlus",
    "AuthMinus",
    "Type",
    "Subject",
    "Target",
    "Action",
    "When",
    "AuthPlusPolicyContent",
    "AuthMinusPolicyContent",
    "AuthPolicy",
    "ParameterName",
    "ParameterValue",
    "ActionIn",
    "ActionOut",
    "ActionResult",
    "ActionName",
    "ActionCondition",
    "ActionFilter",
    "Refrain",
    "RefrainPolicy",
    "PolicyStatement",
  };
}
/* JavaCC - OriginalChecksum=d55d7553a590bcca677146783910e5ec (do not edit this line) */
