package com.ucd.ecs235.compiler;/* Generated By:JJTree&JavaCC: Do not edit this line. PonderConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PonderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INSTANCE = 7;
  /** RegularExpression Id. */
  int AUTHPlUS = 8;
  /** RegularExpression Id. */
  int AUTHMINUS = 9;
  /** RegularExpression Id. */
  int SUBJECT = 10;
  /** RegularExpression Id. */
  int TARGET = 11;
  /** RegularExpression Id. */
  int ACTION = 12;
  /** RegularExpression Id. */
  int WHEN = 13;
  /** RegularExpression Id. */
  int LCURLYBRACE = 14;
  /** RegularExpression Id. */
  int RCURLYBRACE = 15;
  /** RegularExpression Id. */
  int SEMICOLON = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int FOR = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int IN = 21;
  /** RegularExpression Id. */
  int OUT = 22;
  /** RegularExpression Id. */
  int RESULT = 23;
  /** RegularExpression Id. */
  int REFRAIN = 24;
  /** RegularExpression Id. */
  int TYPE = 25;
  /** RegularExpression Id. */
  int DOMAIN = 26;
  /** RegularExpression Id. */
  int ACTIONITEM = 27;
  /** RegularExpression Id. */
  int STRING = 28;
  /** RegularExpression Id. */
  int PARAMETER = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"inst\"",
    "\"auth+\"",
    "\"auth-\"",
    "\"subject\"",
    "\"target\"",
    "\"action\"",
    "\"when\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"else\"",
    "\"for\"",
    "\"if\"",
    "\"in\"",
    "\"out\"",
    "\"result\"",
    "\"refrain\"",
    "<TYPE>",
    "<DOMAIN>",
    "<ACTIONITEM>",
    "<STRING>",
    "<PARAMETER>",
    "\"=\"",
    "\"(\"",
    "\")\"",
  };

}
